# SPDX-FileCopyrightText: Sudo Apt Holdings LLC
# SPDX-License-Identifier: Apache-2.0
defmodule Mix.Tasks.Trinity.Image.Provenance do
  @shortdoc "Writes the headless image's SLSA build provenance predicate (slice 131, AC2)"

  @moduledoc """
  Writes a SLSA provenance v1 predicate (`https://slsa.dev/provenance/v1`) for a built headless
  image, for `scripts/image_supply_chain.sh` to attest to the image's digest
  (`docs/regulated/image-verify.md`).

      mix trinity.image.provenance --image IMAGE --commit SHA --repository URL \\
        --builder-id URI [--ref REF] [--invocation URI] --out provenance.json

  It names **the builder** (`runDetails.builder.id`: the workflow's ref when CI builds), **the
  source repository** (`buildDefinition.externalParameters.repository`) and **the exact source
  commit** (the `git+` entry of `resolvedDependencies`, as `gitCommit`), and lists every other
  input the build took by digest: each resource of `ci/ironbank/hardening_manifest.yaml` and both
  bases of `ci/headless/bases.env`.

  **It refuses an image that does not name the same commit.** `scripts/headless_image.sh build`
  labels the image `org.opencontainers.image.revision` with the commit it was built from, and
  only when no tracked file differed from that commit, since the build stages tracked files as
  they are on disk; otherwise it sets the label empty, because an unset label is inherited from
  the base image, and UBI9 micro's names Red Hat's commit. So an image built from a modified tree
  names no commit, and no provenance can be written for it; an image built from another commit,
  or one whose label is the base's, names a commit other than `--commit`, and none can be written
  for it either. The consumer's sequence makes the same
  comparison from the other side.

  This provenance is generated by a step of the build job and signed with a key that job holds.
  It is SLSA Build L1 provenance and is not claimed as more (`ci/headless/slsa.yaml`).
  """

  use Boundary, classify_to: Trinity
  use Mix.Task

  alias Mix.Tasks.Trinity.Ironbank.Lint

  @manifest "ci/ironbank/hardening_manifest.yaml"
  @bases "ci/headless/bases.env"
  @recipe "ci/ironbank/Dockerfile"
  @revision "org.opencontainers.image.revision"
  @build_type "https://github.com/ScriptKittyOS/Trinity/blob/main/docs/regulated/image-verify.md#build-type-v1"
  @commit ~r/\A[0-9a-f]{40}\z/

  @impl Mix.Task
  def run(argv) do
    {opts, _, _} =
      OptionParser.parse(argv,
        strict: [
          image: :string,
          commit: :string,
          repository: :string,
          builder_id: :string,
          ref: :string,
          invocation: :string,
          out: :string
        ]
      )

    out = opts[:out] || usage!()
    image = opts[:image] || usage!()

    params = %{
      commit: opts[:commit],
      repository: opts[:repository],
      builder_id: opts[:builder_id],
      ref: opts[:ref] || "",
      invocation: opts[:invocation],
      revision_label: revision_label!(image)
    }

    case refusals(params) do
      [] ->
        predicate = predicate(params, read_resources!(@manifest), read_bases!(@bases))
        File.write!(out, Jason.encode_to_iodata!(predicate, pretty: true))

        Mix.shell().info(
          "trinity.image.provenance: #{out} written for #{image} at #{params.commit}"
        )

      found ->
        Enum.each(found, &Mix.shell().error("FAIL AC2: #{&1}"))
        Mix.raise("trinity.image.provenance: #{length(found)} refusal(s)")
    end
  end

  defp usage! do
    Mix.raise(
      "usage: mix trinity.image.provenance --image IMAGE --commit SHA --repository URL " <>
        "--builder-id URI [--ref REF] [--invocation URI] --out FILE"
    )
  end

  defp revision_label!(image) do
    case System.cmd("docker", ["image", "inspect", image, "--format", "{{json .Config.Labels}}"],
           stderr_to_stdout: true
         ) do
      {json, 0} -> json |> Jason.decode!() |> Kernel.||(%{}) |> Map.get(@revision)
      {out, status} -> Mix.raise("docker image inspect #{image} exited #{status}: #{out}")
    end
  end

  @doc "The label an image names its source commit by."
  @spec revision_label() :: String.t()
  def revision_label, do: @revision

  @doc "The `buildType` URI this tree's provenance declares."
  @spec build_type() :: String.t()
  def build_type, do: @build_type

  @doc """
  Why provenance must not be written for these parameters; `[]` when it may. `revision_label` is
  the image's `#{@revision}` label, or nil when it has none; empty is a build that named none.
  """
  @spec refusals(map()) :: [String.t()]
  def refusals(params) do
    commit = params[:commit]

    [
      {is_binary(commit) and Regex.match?(@commit, commit),
       "--commit #{inspect(commit)} is not a full 40-character lowercase git commit"},
      {present?(params[:repository]), "--repository is required"},
      {present?(params[:builder_id]), "--builder-id is required"},
      {params[:revision_label] not in [nil, ""],
       "the image names no commit in its #{@revision} label, so nothing says which commit it " <>
         "was built from (scripts/headless_image.sh names one only for a build of an " <>
         "unmodified tree)"},
      {params[:revision_label] in [nil, ""] or params[:revision_label] == commit,
       "the image's #{@revision} is #{inspect(params[:revision_label])}, not --commit #{commit}"}
    ]
    |> Enum.reject(&elem(&1, 0))
    |> Enum.map(&elem(&1, 1))
  end

  defp present?(value), do: is_binary(value) and value != ""

  @doc """
  The predicate. `resources` are the hardening manifest's resources, `bases` the `KEY=VALUE`
  pairs of the bases file.
  """
  @spec predicate(map(), [map()], %{String.t() => String.t()}) :: map()
  def predicate(params, resources, bases) do
    source = %{
      "uri" => "git+#{params.repository}@#{params.ref}",
      "digest" => %{"gitCommit" => params.commit}
    }

    metadata =
      if params[:invocation], do: %{"invocationId" => params.invocation}, else: %{}

    %{
      "buildDefinition" => %{
        "buildType" => @build_type,
        "externalParameters" => %{
          "repository" => params.repository,
          "ref" => params.ref,
          "recipe" => @recipe,
          "bases" => @bases
        },
        "internalParameters" => %{"buildArgs" => bases},
        "resolvedDependencies" =>
          [source] ++ Enum.map(resources, &resource_dependency/1) ++ base_dependencies(bases)
      },
      "runDetails" => %{
        "builder" => %{"id" => params.builder_id},
        "metadata" => metadata
      }
    }
  end

  defp resource_dependency(%{"url" => url, "filename" => name, "validation" => v}) do
    %{"name" => name, "uri" => url, "digest" => %{v["type"] => v["value"]}}
  end

  # Each base as `oci://registry/image` with the digest its tag argument pins.
  defp base_dependencies(bases) do
    registry = bases["BASE_REGISTRY"]

    for {image_key, tag_key} <- [{"BASE_IMAGE", "BASE_TAG"}, {"BUILDER_IMAGE", "BUILDER_TAG"}],
        image = bases[image_key],
        [_tag, "sha256:" <> hex] <- [String.split(bases[tag_key] || "", "@", parts: 2)] do
      %{"uri" => "oci://#{registry}/#{image}", "digest" => %{"sha256" => hex}}
    end
  end

  @doc "The resources of a hardening manifest."
  @spec read_resources!(Path.t()) :: [map()]
  def read_resources!(path) do
    case YamlElixir.read_from_file(path) do
      {:ok, %{"resources" => resources}} when is_list(resources) -> resources
      other -> Mix.raise("#{path} has no resources list: #{inspect(other)}")
    end
  end

  @doc "The `KEY=VALUE` pairs of a bases file."
  @spec read_bases!(Path.t()) :: %{String.t() => String.t()}
  def read_bases!(path), do: path |> File.read!() |> Lint.env_pairs()
end
