# SPDX-FileCopyrightText: Sudo Apt Holdings LLC
# SPDX-License-Identifier: Apache-2.0
defmodule Mix.Tasks.Trinity.Effects.Catalog do
  @shortdoc "Prints the effect catalogue, or checks the committed artifact against the tree"

  @moduledoc """
  The effect catalogue as a published, versioned artifact (slice 027 AC3 and AC4).

  The population that can cause an effect is the thing a reader of this project most needs and
  is least able to derive: it is spread across a behaviour, a config list, a closed catalogue
  module and an authority adapter. This task collects it into one file, `docs/effects-catalog.md`,
  and the gate fails when that file and the tree disagree. A reader does not have to trust the
  file, because `mix trinity.effects.catalog --check` is the same check they can run.

  **The version is the content.** It is a SHA-256 over the rows, not a number anyone types, so
  two trees with the same effect surface have the same version and a tree that adds a tool has a
  different one whether or not anybody remembered to say so.

  **Read at compile time, not from the registry.** The population is the configured core modules
  and their behaviour callbacks. The running registry also holds dynamic tools (MCP, skills),
  which are exactly what this artifact is a statement *against*: they can propose, and they can
  never be in this list. Reading the registry would let a runtime registration into a
  compile-time claim.

  **`--write` and `--check` refuse outside `MIX_ENV=prod`, and that is the point of them.** The
  artifact is a claim about what *ships*. `config/test.exs` adds scaffolding tools to the same list,
  so a catalogue generated under `:test` names them beside `fs_read`, and a gate running in `:test`
  would then compare a test surface against a production one and fail forever, or, worse, be
  "fixed" by committing the test surface as though it were the product. Measured while writing this
  task: under `:test` the list is five entries longer. Printing works in any environment and stamps
  the environment it read.

  The first draft of this paragraph named one of those scaffolding modules as an example, and slice
  020's census (`test/trinity/tools/registry_test.exs`, "no core module references a test tool")
  failed the build for it. That census is right and the example was not worth it: a shipped tree
  that names its own test scaffolding has a seam a reader has to check.

  ## Usage

      mix trinity.effects.catalog            # print
      mix trinity.effects.catalog --check    # exit 1 if docs/effects-catalog.md differs
      mix trinity.effects.catalog --write    # regenerate docs/effects-catalog.md
  """

  use Boundary, classify_to: Trinity
  use Mix.Task

  @artifact "docs/effects-catalog.md"

  @impl Mix.Task
  def run(argv) do
    Mix.Task.run("app.config")
    rendered = render()

    cond do
      "--check" in argv -> prod!("--check") && check(rendered)
      "--write" in argv -> prod!("--write") && write(rendered)
      true -> Mix.shell().info(rendered)
    end
  end

  defp prod!(flag) do
    if Mix.env() == :prod do
      true
    else
      Mix.raise(
        "#{flag} needs MIX_ENV=prod. This artifact is a claim about what ships, and " <>
          "config/test.exs adds test tools to the same list, so a catalogue built under " <>
          "#{inspect(Mix.env())} would name them. Run `MIX_ENV=prod mix trinity.effects.catalog " <>
          "#{flag}`."
      )
    end
  end

  @doc "Every configured core tool as a row, sorted by name."
  @spec rows() :: [map()]
  def rows do
    :trinity
    |> Application.get_env(:tools, [])
    |> Keyword.get(:modules, [])
    |> Enum.map(&row/1)
    |> Enum.sort_by(& &1.name)
  end

  @doc "The catalogue's version: a SHA-256 over the rows, so the version is the content."
  @spec version([map()]) :: String.t()
  def version(rows) do
    rows
    |> Enum.map_join(
      "\n",
      &"#{&1.name}\t#{&1.risk}\t#{&1.effect}\t#{&1.catalogued}\t#{&1.escalates}"
    )
    |> then(&:crypto.hash(:sha256, &1))
    |> Base.encode16(case: :lower)
    |> binary_part(0, 16)
  end

  defp row(module) do
    Code.ensure_loaded!(module)

    %{
      name: module.name(),
      risk: module.risk(),
      effect: module.effect(),
      catalogued: module.name() in Trinity.Tools.Catalog.names(),
      escalates: function_exported?(module, :escalate, 2),
      module: inspect(module)
    }
  end

  defp render do
    rows = rows()

    """
    <!-- SPDX-FileCopyrightText: Sudo Apt Holdings LLC -->
    <!-- SPDX-License-Identifier: Apache-2.0 -->
    <!-- Generated by `mix trinity.effects.catalog --write`. Do not edit by hand: the gate
         regenerates it and fails when this file and the tree disagree. -->
    # The effect catalogue

    Version `#{version(rows)}`, which is a SHA-256 over the rows below rather than a number anyone
    typed. Two trees with the same effect surface carry the same version. Built from `MIX_ENV=#{Mix.env()}`,
    which `--write` and `--check` require to be `prod`, because this is a statement about what ships.

    This is the population that can cause an effect, in one place. It is otherwise spread across a
    behaviour (`Trinity.Tools.Tool`), a configuration list, a closed catalogue module
    (`Trinity.Tools.Catalog`) and an authority adapter, and a reader would have to assemble it to
    check any claim this project makes about least privilege.

    What is *not* here is the point of it. Tools registered at runtime, from an MCP server or a
    skill, never appear: they can propose a call, and the membrane refuses an effectful one that is
    not in this list. `mix trinity.effects.catalog --check` is in the quality gate, so a tool added
    without this file changing fails the build.

    | Tool | Risk tier | Effect class | In the closed catalogue | Can escalate | Module |
    |---|---|---|---|---|---|
    #{Enum.map_join(rows, "\n", &line/1)}

    ## How to read the columns

    - **Risk tier** is a function of the tool's *name* alone. Arguments can raise what a call
      requires (the next column); they can never change the tier.
    - **Effect class** is what the membrane reads. `:none` never reaches `Trinity.Effects`;
      `:artifact` and `:catalog` both cross it and both leave a signed receipt.
    - **In the closed catalogue** means the name is in `Trinity.Tools.Catalog`, the compile-time
      list of external effects. The registry refuses a runtime registration claiming `:catalog`.
    - **Can escalate** means the tool implements `escalate/2`, which may raise a single call's
      required tier from its arguments. It is one-way by the behaviour's contract.

    ## Where execution happens

    Under the default authority (`TRINITY_AUTHORITY=local`, ADR-0010) `Trinity.Authority.Local` is
    the executor and runs the tool's own `execute/2`. Under an external authority adapter Trinity
    keeps no executor for catalogued effects: it proposes, the adapter decides and acts, and the
    census test for that mode asserts the absence rather than describing it. The mode is chosen
    once at boot, recorded in the boot receipt, and no runtime path changes it.
    """
  end

  defp line(r) do
    "| `#{r.name}` | `#{r.risk}` | `#{r.effect}` | #{yes(r.catalogued)} | #{yes(r.escalates)} | `#{r.module}` |"
  end

  defp yes(true), do: "yes"
  defp yes(false), do: "no"

  defp write(rendered) do
    File.write!(@artifact, rendered)
    Mix.shell().info("trinity.effects.catalog: wrote #{@artifact}")
  end

  defp check(rendered) do
    case File.read(@artifact) do
      {:ok, ^rendered} ->
        Mix.shell().info("trinity.effects.catalog: OK. #{@artifact} matches the tree")

      {:ok, _other} ->
        Mix.raise(
          "#{@artifact} does not match the tree. The effect surface changed and the published " <>
            "artifact did not. Run `mix trinity.effects.catalog --write` and commit the result."
        )

      {:error, :enoent} ->
        Mix.raise("#{@artifact} is missing. Run `mix trinity.effects.catalog --write`.")
    end
  end
end
