# SPDX-FileCopyrightText: Sudo Apt Holdings LLC
# SPDX-License-Identifier: Apache-2.0
defmodule Mix.Tasks.Versions.Gen do
  @shortdoc "Regenerates VERSIONS.md's tables from Trinity.Versions and mix.lock"

  @moduledoc """
  Writes the generated block in `VERSIONS.md` from `Trinity.Versions`: finding M6's one-way
  data flow, so the prose cannot drift from the checked data.

  ## The verification mark is derived

  A row is marked ✅ when its package is present in `mix.lock`, read through
  `Mix.Dep.Lock.read/0`, and 🔍 when it is absent. Toolchain rows are marked from
  `.tool-versions` instead, since they are not hex packages. **Nothing is marked by hand**, so
  the mark cannot outlive the fact it asserts, which is what finding B3 caught twice.

  `--check` regenerates in memory and fails if the file differs, which is how the gate asserts
  the tables match the data without parsing the markdown.
  """

  use Boundary, classify_to: Trinity
  use Mix.Task

  @path "VERSIONS.md"
  @begin "<!-- versions:begin -->"
  @stop "<!-- versions:end -->"

  @impl Mix.Task
  def run(argv) do
    {opts, _} = OptionParser.parse!(argv, strict: [check: :boolean])
    current = File.read!(@path)
    updated = splice(current, render(locked()))

    cond do
      current == updated ->
        Mix.shell().info(
          "versions.gen: VERSIONS.md already matches Trinity.Versions and mix.lock"
        )

      opts[:check] ->
        Mix.raise("versions.gen --check: #{@path} does not match. Run `mix versions.gen`.")

      true ->
        File.write!(@path, updated)
        Mix.shell().info("versions.gen: regenerated #{@path}")
    end
  end

  @doc "Package names present in `mix.lock`."
  @spec locked() :: MapSet.t(String.t())
  def locked do
    Mix.Dep.Lock.read() |> Map.keys() |> Enum.map(&Atom.to_string/1) |> MapSet.new()
  end

  @doc """
  The mark for one row: ✅ when the lock carries it, 🔍 when it does not.

  A `:toolchain` row is never a hex package, so it is marked from its own `:from`:

    * `{:file, path, needle}`: ✅ naming that file when the file carries the pin, ❌ when it
      does not. Before Slice 001 line 3 this clause was the constant `✅ \`.tool-versions\``
      for every toolchain row, which marked Rust and Zig against a file carrying neither.
    * `{:command, cmd}`: 📐 naming the command. Never ✅: nothing at this sha verifies it, and
      a mark that says otherwise is the claim finding B3 caught.
  """
  @spec mark(map(), :toolchain | :deps, MapSet.t(String.t())) :: String.t()
  def mark(%{from: {:file, path, needle}}, :toolchain, _locked) do
    if File.exists?(path) and String.contains?(File.read!(path), needle),
      do: "✅ `#{path}`",
      else: "❌ `#{path}` does not carry `#{needle}`"
  end

  def mark(%{from: {:command, cmd}}, :toolchain, _locked), do: "📐 `#{cmd}`"

  def mark(row, :toolchain, _locked),
    do: Mix.raise("versions.gen: toolchain row #{inspect(row[:name])} states no :from source")

  def mark(%{lock: nil}, :deps, _locked), do: "🔍 not a single package"

  def mark(%{lock: key}, :deps, locked) do
    if MapSet.member?(locked, key), do: "✅ in `mix.lock`", else: "🔍 not yet a dependency"
  end

  @doc "The generated block, between its markers."
  @spec render(MapSet.t(String.t())) :: String.t()
  def render(locked) do
    body =
      Enum.map_join(Trinity.Versions.tables(), "\n", fn %{title: t, kind: kind, rows: rows} ->
        """
        ### #{t}

        | Name | Pin | Verified | Note |
        |---|---|---|---|
        """ <>
          Enum.map_join(rows, "\n", fn r ->
            "| `#{r.name}` | #{r.pin} | #{mark(r, kind, locked)} | #{r.note} |"
          end) <> "\n"
      end)

    """
    #{@begin}
    <!-- GENERATED by `mix versions.gen` from lib/trinity/versions.ex and mix.lock.
         Do not edit by hand: `mix versions.gen --check` is a gate step and fails on any drift.

         The Verified column is DERIVED, never typed:
           ✅ `in mix.lock`   the package is present in mix.lock at this sha
           🔍 `not yet ...`   the package is absent; the slice that adds it will flip this
           ✅ `<file>`        a toolchain pin, and that file in the tree carries it
           ❌ `<file>` ...    a toolchain row naming a file that does NOT carry its pin
           📐 `<command>`     no file in the tree pins this; only that command answers, and
                              its output and exit code live in the slice PROOF.md. Never ✅.

         Deriving commands:
           $ mix versions.gen --check     # asserts this block matches the data
           $ mix versions.verify          # asserts every pin is satisfied by mix.lock
         Marks last derived: 2026-09-06. -->

    #{body}#{@stop}\
    """
  end

  defp splice(current, block) do
    case String.split(current, [@begin, @stop]) do
      [before, _old, rest] -> before <> block <> rest
      [_] -> String.trim_trailing(current) <> "\n\n" <> block <> "\n"
      _ -> Mix.raise("#{@path}: malformed generated-block markers")
    end
  end
end
