# SPDX-FileCopyrightText: Sudo Apt Holdings LLC
# SPDX-License-Identifier: Apache-2.0
defmodule Mix.Tasks.Versions.Gen do
  @shortdoc "Regenerates VERSIONS.md's pinned tables from Trinity.Versions"

  @moduledoc """
  Writes the generated block in `VERSIONS.md` from `Trinity.Versions` — finding M6's one-way
  data flow, so the prose cannot drift from the checked data.

  Only the block between the markers is generated. The rest of `VERSIONS.md` is hand-written
  and stays that way: it carries rows for dependencies no slice has added yet, and generating
  the whole file from a pin list that does not include them would delete them.

  `--check` regenerates in memory and fails if the file differs, which is how the gate can
  assert the table matches the data without rewriting the file.
  """

  use Boundary, classify_to: Trinity
  use Mix.Task

  @path "VERSIONS.md"
  @begin "<!-- versions:begin -->"
  @stop "<!-- versions:end -->"

  @impl Mix.Task
  def run(argv) do
    {opts, _} = OptionParser.parse!(argv, strict: [check: :boolean])
    current = File.read!(@path)
    updated = splice(current, render())

    cond do
      current == updated ->
        Mix.shell().info("versions.gen: VERSIONS.md already matches Trinity.Versions")

      opts[:check] ->
        Mix.raise(
          "versions.gen --check: #{@path} does not match Trinity.Versions. Run `mix versions.gen`."
        )

      true ->
        File.write!(@path, updated)
        Mix.shell().info("versions.gen: regenerated the block in #{@path}")
    end
  end

  @doc "The generated block, between its markers."
  @spec render() :: String.t()
  def render do
    rows = fn list ->
      Enum.map_join(list, "\n", fn %{name: n, pin: p, note: note} ->
        "| `#{n}` | **#{p}** | #{note} |"
      end)
    end

    """
    #{@begin}
    <!-- Generated by `mix versions.gen` from lib/trinity/versions.ex. Do not edit by hand:
         `mix versions.gen --check` fails the gate if this block and the module disagree. -->

    ### Toolchain, pinned in `.tool-versions`

    | Component | Pin | Note |
    |---|---|---|
    #{rows.(Trinity.Versions.toolchain())}

    ### Dependencies added at slice 000

    | Package | Pin | Note |
    |---|---|---|
    #{rows.(Trinity.Versions.deps())}
    #{@stop}\
    """
  end

  defp splice(current, block) do
    case String.split(current, [@begin, @stop]) do
      [before, _old, rest] -> before <> block <> rest
      [_] -> String.trim_trailing(current) <> "\n\n" <> block <> "\n"
      _ -> Mix.raise("#{@path}: malformed generated-block markers")
    end
  end
end
