# SPDX-FileCopyrightText: Sudo Apt Holdings LLC
# SPDX-License-Identifier: Apache-2.0
import Config

# Configure your database
config :trinity, Trinity.Repo,
  database: Path.expand("../trinity_dev.db", __DIR__),
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :trinity, TrinityWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "pEceiX84jrYwBFOP3ahGMX2Fwkza/3kU0AHhXBIi2JNnbu7muM20VzLmWLCddSwi",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:trinity, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:trinity, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :trinity, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Slice 001. `ex_tauri` is a :dev-only dependency and warns on every `mix phx.server` start
# until it is configured, which made the plain dev server nag about a desktop shell it is not
# running. Configuring it here silences that without involving Tauri in the plain server: none
# of these keys is read unless a `mix ex_tauri.*` task runs.
#
# `:version` is the **Tauri** version, and only its major is consumed — `extract_cli_version/1`
# takes the major and installs `tauri-cli ^<major>`, which resolved to 2.11.4 on 2026-09-06
# (VERSIONS.md carries that row with its deriving command). 2.5.1 is ex_tauri's own suggested
# value and is kept so this file does not invent a pin the library does not use.
config :ex_tauri,
  version: "2.5.1",
  app_name: "Trinity",
  host: "127.0.0.1",
  port: 4000
