# SPDX-FileCopyrightText: Sudo Apt Holdings LLC
# SPDX-License-Identifier: Apache-2.0
"""Writes lib/trinity/memory/word_piece/tables.ex from the reference tokenizer's own behaviour.

Slice 133. The pure-Elixir WordPiece must give the ids Hugging Face `tokenizers` gives, and that
library classifies characters with its own Unicode tables (the `unicode_categories` crate for
control, punctuation and non-spacing marks; `unicode-normalization-alignments` for NFD; Rust's std
for whitespace and lowercase), which are not the Unicode version OTP ships. So the tables are not
written from a Unicode database at all: every code point is put through the reference
normaliser and pre-tokeniser, one at a time, and what they do is recorded.

Run it with the pinned reference (requirements in the slice's NOTES), outside the tree's own
environment, isolated:

    python -I scripts/static/wordpiece_tables.py > lib/trinity/memory/word_piece/tables.ex

It reads no model file: the tables depend on the library, not on any vocabulary or weights.
"""
import sys

import tokenizers
from tokenizers.normalizers import BertNormalizer
from tokenizers.pre_tokenizers import BertPreTokenizer

NORM = BertNormalizer(clean_text=True, handle_chinese_chars=True, strip_accents=None, lowercase=True)
PRE = BertPreTokenizer()

HANGUL_FIRST, HANGUL_LAST = 0xAC00, 0xD7A3


def codepoints():
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        yield cp


def hangul_nfd(cp):
    s = cp - HANGUL_FIRST
    l, v, t = 0x1100 + s // 588, 0x1161 + (s % 588) // 28, 0x11A7 + s % 28
    return chr(l) + chr(v) + (chr(t) if t != 0x11A7 else "")


def ranges(cps):
    out = []
    for cp in sorted(cps):
        if out and out[-1][1] == cp - 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return out


def main():
    remove, space, cjk, punct, ws = [], [], [], [], []
    mapping = {}
    for cp in codepoints():
        c = chr(cp)
        out = NORM.normalize_str(c)
        if out == "" and cp in range(HANGUL_FIRST, HANGUL_LAST + 1):
            raise SystemExit(f"unexpected removal of a Hangul syllable {cp:#x}")
        if HANGUL_FIRST <= cp <= HANGUL_LAST:
            if out != hangul_nfd(cp):
                raise SystemExit(f"Hangul {cp:#x} is not the algorithmic decomposition: {out!r}")
        elif out == "":
            remove.append(cp)
        elif out == " ":
            space.append(cp)
        elif out == " " + c + " ":
            cjk.append(cp)
        elif out != c:
            mapping[cp] = out
        # The pre-tokeniser: whitespace splits and is dropped, punctuation is isolated.
        pieces = [p for p, _ in PRE.pre_tokenize_str("a" + c + "b")]
        if pieces == ["a", "b"]:
            ws.append(cp)
        elif pieces == ["a", c, "b"]:
            punct.append(cp)
        elif pieces != ["a" + c + "b"]:
            raise SystemExit(f"unexpected pre-tokenisation of {cp:#x}: {pieces!r}")

    def ex_ranges(name, cps):
        body = ",\n    ".join(f"{{0x{a:X}, 0x{b:X}}}" for a, b in ranges(cps))
        return f"  @{name} [\n    {body}\n  ]\n"

    def ex_string(s):
        return '"' + "".join(f"\\u{{{ord(ch):X}}}" for ch in s) + '"'

    entries = ",\n    ".join(f"0x{cp:X} => {ex_string(v)}" for cp, v in sorted(mapping.items()))

    sys.stdout.write(f'''# SPDX-FileCopyrightText: Sudo Apt Holdings LLC
# SPDX-License-Identifier: Apache-2.0
# GENERATED by scripts/static/wordpiece_tables.py from tokenizers {tokenizers.__version__}. Do not edit.
defmodule Trinity.Memory.WordPiece.Tables do
  @moduledoc """
  What the reference BERT normaliser and pre-tokeniser do to each code point (slice 133),
  recorded by putting every code point through Hugging Face `tokenizers` {tokenizers.__version__}
  one at a time (`scripts/static/wordpiece_tables.py`). Generated, not written from a Unicode
  database: the reference classifies with its own, older, tables, and parity means matching
  them rather than OTP's.

  Hangul syllables (U+AC00 to U+D7A3) are not listed: the generator checked that the reference
  decomposes every one of them algorithmically, and `Trinity.Memory.WordPiece` does the same.
  """

{ex_ranges("remove", remove)}
{ex_ranges("space", space)}
{ex_ranges("cjk", cjk)}
{ex_ranges("punct", punct)}
{ex_ranges("ws", ws)}
  @mapping %{{
    {entries}
  }}

  @doc "Code points the cleaning step removes (control, format, private use, NUL, U+FFFD)."
  @spec remove() :: [{{non_neg_integer(), non_neg_integer()}}]
  def remove, do: @remove

  @doc "Code points the cleaning step turns into a space."
  @spec space() :: [{{non_neg_integer(), non_neg_integer()}}]
  def space, do: @space

  @doc "Code points padded with spaces as CJK ideographs."
  @spec cjk() :: [{{non_neg_integer(), non_neg_integer()}}]
  def cjk, do: @cjk

  @doc "Code points the pre-tokeniser isolates as punctuation."
  @spec punct() :: [{{non_neg_integer(), non_neg_integer()}}]
  def punct, do: @punct

  @doc "Code points the pre-tokeniser splits on as whitespace."
  @spec ws() :: [{{non_neg_integer(), non_neg_integer()}}]
  def ws, do: @ws

  @doc "Every other code point whose normalised form is not itself: NFD, marks stripped, lowercased."
  @spec mapping() :: %{{non_neg_integer() => String.t()}}
  def mapping, do: @mapping
end
''')
    print(f"remove={len(remove)} space={len(space)} cjk={len(cjk)} punct={len(punct)} ws={len(ws)} mapping={len(mapping)}", file=sys.stderr)


if __name__ == "__main__":
    main()
