# SPDX-FileCopyrightText: Sudo Apt Holdings LLC
# SPDX-License-Identifier: Apache-2.0
defmodule TrinityWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :trinity

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  # Slice 136: encrypted as well as signed (the OpenID Connect login keeps its PKCE verifier and
  # nonce here between the redirect and the callback), and `SameSite`/`Secure` chosen per request
  # by `TrinityWeb.Plugs.Session`.
  @session_options [
    store: :cookie,
    key: "_trinity_key",
    signing_salt: "NacAdZLW",
    encryption_salt: "q8N3vXwT",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Slice 136: a request whose Host is not this machine's own is refused before anything else
  # sees it (DNS rebinding; Phoenix and Bandit have no such check). The websocket transports
  # above are dispatched before any plug and are held by `check_origin` instead.
  plug TrinityWeb.Plugs.HostAllowList

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :trinity,
    gzip: not code_reloading?,
    only: TrinityWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :trinity
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Slice 061: Trinity as an MCP server, at POST /mcp, ahead of the parsers: the core's
  # transport reads the raw body itself (its size bound, its nesting bound, its duplicate-key
  # refusal), so the body must reach it unread. Every other request passes through.
  plug Trinity.MCP.Server.Plug

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug TrinityWeb.Plugs.Session, @session_options
  # Slice 136: no principal, no route (TrinityWeb.Auth).
  plug TrinityWeb.Auth.Gate
  plug TrinityWeb.Router
end
